[build]
  command = "yarn --cwd frontend install --frozen-lockfile && yarn --cwd frontend build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200