[build]
  command = "yarn --cwd frontend install --frozen-lockfile && yarn --cwd frontend build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://dropship-control-3.preview.emergentagent.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200